# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['src/gui/main_window.py'],
    pathex=['src'],
    binaries=[],
    datas=[
        ('src', 'src'),
        ('venv_py39/Lib/site-packages/paddleocr', 'paddleocr'),
        ('venv_py39/Lib/site-packages/paddleocr/tools', 'paddleocr/tools'),
        ('venv_py39/Lib/site-packages/requests', 'requests'),
        ('venv_py39/Lib/site-packages/urllib3', 'urllib3'),
        ('venv_py39/Lib/site-packages/charset_normalizer', 'charset_normalizer'),
        ('venv_py39/Lib/site-packages/certifi', 'certifi'),
        ('venv_py39/Lib/site-packages/idna', 'idna'),
        ('venv_py39/Lib/site-packages/PIL', 'PIL'),
        ('venv_py39/Lib/site-packages/shapely', 'shapely'),
        ('venv_py39/Lib/site-packages/numpy', 'numpy'),
        ('venv_py39/Lib/site-packages/pyclipper', 'pyclipper'),
        ('venv_py39/Lib/site-packages/skimage', 'skimage'),
        ('venv_py39/Lib/site-packages/scipy', 'scipy'),
        ('venv_py39/Lib/site-packages/tifffile', 'tifffile'),
        ('venv_py39/Lib/site-packages/imageio', 'imageio'),
        ('venv_py39/Lib/site-packages/imgaug', 'imgaug'),
        ('venv_py39/Lib/site-packages/albumentations', 'albumentations'),
        ('venv_py39/Lib/site-packages/lmdb', 'lmdb'),
        ('venv_py39/Lib/site-packages/docx', 'docx'),
    ],
    hiddenimports=[
        'paddleocr',
        'paddleocr.tools',
        'requests',
        'urllib3',
        'charset_normalizer',
        'certifi',
        'idna',
        'PIL',
        'PIL._imaging',
        'PIL.Image',
        'PIL.ImageDraw',
        'PIL.ImageFont',
        'shapely',
        'shapely.geometry',
        'shapely.ops',
        'shapely.speedups._speedups',
        'shapely.impl',
        'numpy',
        'geos',
        'pyclipper',
        'skimage',
        'skimage.morphology',
        'skimage.morphology._skeletonize',
        'scipy',
        'scipy.ndimage',
        'tifffile',
        'imageio',
        'imgaug',
        'imgaug.augmenters',
        'albumentations',
        'albumentations.core',
        'albumentations.augmentations',
        'lmdb',
        'docx',
        'docx.document',
        'docx.oxml',
        'docx.oxml.text.paragraph',
        'docx.oxml.table',
        'docx.table',
        'docx.text.paragraph',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='subtitle_extractor',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)